version: '3'
services:
  app:
    build:
      context: ./src/GeositeFramework
    working_dir: /usr/src/
    ports:
      - "54633:54633"
    volumes:
        - ./src/GeositeFramework:/usr/src/src/GeositeFramework
        - ./scripts:/usr/src/scripts
        - ./dist:/usr/dist
