#!/bin/bash

set -e

if [[ -n "${GEOSITE_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n "Usage: $(basename "$0") OPTION(S)
        Starts the python development server.

        Options:
        -d     Start server within a python docker container"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        if [ "${1:-}" = "-d" ]
        then
            docker-compose -f docker-compose.yml up
        else
            python ./scripts/server.py
        fi
    fi
fi
